version: "3.5"

services:
    test:
        image: golang:1.14
        volumes:
            - .:/go/src/app
        working_dir: /go/src/app
        depends_on:
            - minio
        environment:
            - "AWS_S3_REGION=${AWS_S3_REGION}"
            - "AWS_S3_BUCKET=${AWS_S3_BUCKET}"
            - "AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}"
            - "AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}"
            - "AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}"
            - "COVERALLS_TOKEN=${COVERALLS_TOKEN:-}"
            - "TRAVIS_BRANCH=${TRAVIS_BRANCH:-}"

    minio:
        image: minio/minio:latest
        command: server /data
        ports:
            - "9000:9000"
        environment:
            - MINIO_DOMAIN=minio
            - "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
            - "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
        networks:
            default:
                aliases:
                    - minio
                    - test.minio
                    - dest.minio
